# This is a doc written by Jupyter Notebook.

In [2]:
import torch

In [3]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [7]:
i = torch.ones((5, 3), dtype = torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [9]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2) 
print("a random tensor:")
print(r1)

r2 = torch.rand(2, 2)
print("a different tensor generated randomly:")
print(r2)

torch.manual_seed(1729)
r3 = torch.rand(2, 2)
print("this tensor should be the same with r1:")
print(r3)

a random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])
a different tensor generated randomly:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
this tensor should be the same with r1:
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [12]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2  # every element is multiplies by 2
print(twos)

threes = ones + twos
print(threes)
print(threes.shape)
'''
r1 = torch.rand(2, 3)
r2 = torch.rand(3, 2)
r3 = r2 + r1
'''

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


'\nr1 = torch.rand(2, 3)\nr2 = torch.rand(3, 2)\nr3 = r2 + r1\n'

In [18]:
x = torch.randn(1, 10)  # randn includes negative numbers
prev_h = torch.randn(1, 20) 
W_h = torch.randn(20, 20)
W_x = torch.randn(20, 10)

i2h = torch.mm(W_x, x.t())
h2h = torch.mm(W_h, prev_h.t())
next_h = i2h + h2h
next_h = next_h.tanh()

loss = next_h.sum()
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn