In [39]:
import torch
import numpy as np

# Tensor Initialization

In [8]:
data = [[1, 2], [3, 4]]    # ctrl + alt + enter for execuitng current cell
x_data = torch.tensor(data)
print(x_data)
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [9]:
x_ones = torch.ones_like(x_data)  # with the properties(shape and datatype) of x_data
print(f"ones tensor with x_data properties: \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # override the datatype of x_data
print(f"random tensor: \n {x_rand} \n")

ones tensor with x_data properties: 
 tensor([[1, 1],
        [1, 1]])

random tensor: 
 tensor([[0.0707, 0.5037],
        [0.6552, 0.2219]]) 



In [15]:
shape = (2, 3, 4)
rand_tensor = torch.rand(shape)
print(f"random tensor with a specific shape {shape}:\n{rand_tensor}")

random tensor with a specific shape (2, 3, 4):
tensor([[[0.4513, 0.3729, 0.1324, 0.5481],
         [0.7381, 0.3526, 0.8635, 0.7667],
         [0.5008, 0.8496, 0.8019, 0.5826]],

        [[0.5969, 0.1085, 0.2404, 0.4939],
         [0.1927, 0.0222, 0.9756, 0.1507],
         [0.6266, 0.0494, 0.8774, 0.0993]]])


In [17]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [18]:
# we move our tensor to the GPU if available:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [35]:
tensor1 = torch.ones(4, 4)
tensor2 = torch.ones(4, 4)
tensor1[:,1] = 0
tensor2[2,:] = 3
print(tensor1)
print(tensor2)
tensor3 = torch.cat([tensor1, tensor2], dim=1)
print(tensor3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [3., 3., 3., 3.],
        [1., 1., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 1., 1.],
        [1., 0., 1., 1., 3., 3., 3., 3.],
        [1., 0., 1., 1., 1., 1., 1., 1.]])


In [36]:
# this computes the element-wise product:
print(f"tensor.num(tensor) \n: {tensor1.mul(tensor1)}\n")
# alternatively:
print(f"tensor*tensor \n {tensor1*tensor1}")

tensor.num(tensor) 
: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor*tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [42]:
 # this computes the matrix multiplication between tensors:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)}")
print(tensor)
print(tensor.T)
# alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


**in-place operations save memory, but can be problematic when computing derivatives because inmmediate loss of history** <br>
**for example:** <br>
`x.copy_(y)` and `x.t_()` that have a `_` suffix. 

In [43]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
